# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.url }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Extension Workshop
description: >- # this means to ignore newlines until "url:"
  Firefox Extension Workshop. Make the web do what you want. If you can dream it,
  our open souce API and your HTML, CSS, and JavaScript skills can make it happen.
url: "https://extensionsworkshop.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-77033033-24

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.md

#defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true

# Build settings
markdown: kramdown
# theme: minima
plugins:
#  - jekyll-feed

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Search input placeholder
  placeholder: 'Search in MDN Web Docs...'

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:

  # If defined and browserify and uglifyify are installed, the plugin will
  # generate a bundle to define the renderJekyllPagesApiSearchResults
  # function.
  browserify:
    source: _assets/js/my-search.js
    target: assets/js/my-search-bundle.js

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - renovate.json
  - rvm-installer
  - rvm-installer.asc
  - yarn-error.log
  - yarn.lock

assets:
  compression: true
  sources:
    - _assets/img
    - _assets/css
    - _assets/fonts
    - _assets/js
    - node_modules/foundation-sites/scss
    - node_modules/slick-carousel/slick
    - node_modules/jquery/dist
    - node_modules/dompurify/dist
    - node_modules/lunr/
    - node_modules/velocity-animate
  defaults:
    js:
      integrity: true
    css:
      integrity: false
    img:
      integrity: false
  plugins:
    img:
      optim:
        jekyll:
          verbose: false
          pngout: false
          svgo:
