# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.url }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Firefox Extension Workshop
description: >- # this means to ignore newlines until "url:"
  Extension Workshop
url: "https://extensionworkshop.com" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-77033033-24

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.md

#defaults:
#  - scope:
#      path: "assets/img"
#    values:
#      image: true

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: false

# theme: minima
plugins:
  - jekyll-target-blank
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - README.md
  - renovate.json
  - rvm-installer
  - rvm-installer.asc
  - yarn-error.log
  - yarn.lock

assets:
  compression: true
  sources:
    - _assets/img
    - _assets/css
    - _assets/fonts
    - _assets/js
    - node_modules/foundation-sites/scss
    - node_modules/slick-carousel/slick
    - node_modules/jquery/dist
    - node_modules/dompurify/dist
    - node_modules/lunr/
    - node_modules/velocity-animate
  defaults:
    js:
      integrity: true
    css:
      integrity: false
    img:
      integrity: false
  plugins:
    img:
      optim:
        jekyll:
          verbose: false
          pngout: false
          svgo:
